server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlserver://192.168.0.227:1433;database=UPCN_RRHH_PRUE;encrypt=false;trustServerCertificate=true
    username: UPCN-admin
    password: UPCN-2018+
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true

# Configuracion de la aplicacion
app:
  # Maximo numero de rectangulos a mostrar en el canvas
  max-rectangles: 50
  
  # Cache de dependencias
  cache:
    # Tiempo de expiracion en minutos
    expiration-minutes: 60

# CORS para desarrollo
cors:
  allowed-origins: http://localhost:5173
